{% set version = "0.7.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gprofiler
  version: {{ version|replace("-", "_") }}

source:
  fn: gProfileR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gProfileR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gProfileR/gProfileR_{{ version }}.tar.gz
  sha256: 9364e0721889e101cf24ff3158a48e3c6691dd81f6ff281a5504587ddf043bc0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-rcurl
    - r-plyr

  run:
    - r-base
    - r-rcurl
    - r-plyr

test:
  commands:
    - $R -e "library('gProfileR')"           # [not win]
    - "\"%R%\" -e \"library('gProfileR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gProfileR
  license: GPL (>= 2)
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  summary: Functional enrichment analysis, gene identifier conversion and mapping homologous
    genes across related organisms via the 'g:Profiler' toolkit (<https://biit.cs.ut.ee/gprofiler/>).
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
