{% set version = "0.6.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gprofiler
  version: {{ version|replace("-", "_") }}

source:
  fn: gProfileR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gProfileR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gProfileR/gProfileR_{{ version }}.tar.gz
  sha256: 35e60d462e26c445883ebc79ba0aa91b9b27aaf7d95f3ee0f8855dda56a9def4

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-rcurl
    - r-plyr

  run:
    - r-base
    - r-rcurl
    - r-plyr

test:
  commands:
    - $R -e "library('gProfileR')"  # [not win]
    - "\"%R%\" -e \"library('gProfileR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gProfileR
  license: GPL (>= 2)
  summary: Functional enrichment analysis, gene identifier conversion and mapping homologous
    genes across related organisms via the 'g:Profiler' toolkit (http://biit.cs.ut.ee/gprofiler/).
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
