appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: hNEJeWOBVCFRtuqATnE9wAbWxkzVLyhsR7BIXqVITY5OQ5kz52+9CBXHTYb9q9DLGNwtuJMugE7kNpJPCgpmlUmVYhxe+QW0/dYMTSBaVvTxBnKKcC7zXV7sDVJbby1gjTeOU9gV5InPIGVuY3b4ZdJ7GOFyd+k3b0wQzflwUgLgFpRMx3/NYUOdV9xFrCyakwTLbAv1x8QM57zFPbcgr+LsCdQlJ1GdvyxjtgFHHwbzBDWk3J5fpxeOKEaP9kF7AYFX01IH7wBP84DS4t7Gn3ZMmGSA3A8rvU75kzK8sSxN+I0rPgjng7gR4upqbIBQ59HQJytZNnfnIM/yPMfCIdneCHDJ6tztQ4nAY8E61BVC6pXN47h9kBxZbDlZPNiyYUu/jwal9clJaEUTb2Mi3Jkb1lVPTI8sWNNzS4FlsgdZObtvx2S9gnBWcN7dKIqcYSBADmplC0KAlODRCd51ic7Aj5QXc9M2w6jfUBBi5OeyGoC+XQEJmfJoGz0V5Tt+tbCuOjT5BFg5VH1TU8HDorCNVstmu/BMmr1cNvu1K7mmixbIrngWP4DbCxbQ35JplzuJJ4QGCaVzxbCwhdnl8xowTAuX81DWZ/7wUdlleaOsj/A6TcmladJz0XYtCGvH4M+Ex5CyK0DwyheokB3TlRDc+dnnIV48jdYeaNdaB6Q=}
bot:
  automerge: true
